### ISSUE TITLE
dataset question

### ISSUE THREAD

**Issue by 1429904852** [HKUST-KnowComp/VWS-DMSC#1]
The first or last label in the dataset is the sentiment polarity of the document?
![2019-12-18 13-00-20屏幕截图](https://user-images.githubusercontent.com/34151761/71057074-61551b80-2196-11ea-9e9b-b4673946c5e5.png)

**Comment by ZiqianZENG** [comment]
The first label in the dataset is the sentiment polarity of the document.

**Comment by 1429904852** [comment]
OK, thanks
